const shared = {
  en: {
    brandSubtitle: 'Intelligent concessional scheme matcher', location: 'India', eyebrowWorkspace: 'Financial assistance workspace', headingMain1: 'Good afternoon.', headingMain2: "Let's make your plan possible.", introCopy: 'Describe your requirement in your own words. We will turn it into an eligibility check and practical next steps.', metricRequired: 'Required', metricIncome: 'Annual income', metricSector: 'Sector', metricStatus: 'Current status', statusEligible: 'Eligible', statusReview: 'Review needed', statusReady: 'Ready to analyse', eyebrowSupport: 'Find support', titleLookingFor: "Tell us what you're looking for", btnStructured: 'Structured profile', btnNatural: 'Natural language', btnVoice: 'Voice', btnAnalyse: 'Analyse eligibility', btnAnalysing: 'Analysing profile...', labelTryExample: 'Try an example', labelUnderstanding: 'Understanding', labelRequirement: 'requirement', labelAddRequirement: 'Add requirement', labelIncome: 'income', labelAddIncome: 'Add income', eyebrowAssessment: 'Assessment', titleOutlook: 'Your financial outlook', titleResultsPlaceholder: 'Results will appear here', btnNewAssessment: 'New assessment', descPlaceholderResults: 'Your eligibility result, suggested financial terms and support partners will appear after analysis.', purposeGeneral: 'General', purposeTailoring: 'Tailoring', purposeDairy: 'Dairy', purposeWelding: 'Welding', purposeFarming: 'Farming', purposeEducation: 'Education', translating: 'Translating...', assessmentComplete: 'Assessment complete', voiceUnsupported: 'Voice input is not supported in this browser. Please use text or structured profile.', requestRequired: 'Please tell us what you need support for.', serviceUnavailable: 'The service is currently unavailable.'
  },
  hi: {
    brandSubtitle: 'बुद्धिमान रियायती योजना मिलान', location: 'भारत', eyebrowWorkspace: 'वित्तीय सहायता कार्यक्षेत्र', headingMain1: 'नमस्कार।', headingMain2: 'आइए आपकी योजना को संभव बनाएं।', introCopy: 'अपनी आवश्यकता अपने शब्दों में बताएं। हम इसे पात्रता जांच और व्यावहारिक अगले चरणों में बदल देंगे।', metricRequired: 'आवश्यक राशि', metricIncome: 'वार्षिक आय', metricSector: 'क्षेत्र', metricStatus: 'वर्तमान स्थिति', statusEligible: 'पात्र', statusReview: 'समीक्षा आवश्यक', statusReady: 'विश्लेषण के लिए तैयार', eyebrowSupport: 'सहायता खोजें', titleLookingFor: 'आप क्या खोज रहे हैं बताएं', btnStructured: 'संरचित प्रोफ़ाइल', btnNatural: 'प्राकृतिक भाषा', btnVoice: 'आवाज़', btnAnalyse: 'पात्रता जांचें', btnAnalysing: 'प्रोफ़ाइल का विश्लेषण हो रहा है...', labelTryExample: 'एक उदाहरण आज़माएं', labelUnderstanding: 'समझ', labelRequirement: 'आवश्यकता', labelAddRequirement: 'आवश्यकता जोड़ें', labelIncome: 'आय', labelAddIncome: 'आय जोड़ें', eyebrowAssessment: 'आकलन', titleOutlook: 'आपका वित्तीय परिदृश्य', titleResultsPlaceholder: 'परिणाम यहां दिखाई देंगे', btnNewAssessment: 'नया आकलन', descPlaceholderResults: 'विश्लेषण के बाद आपकी पात्रता, वित्तीय शर्तें और सहायता साझेदार दिखाई देंगे।', purposeGeneral: 'सामान्य', purposeTailoring: 'दर्जी', purposeDairy: 'डेयरी', purposeWelding: 'वेल्डिंग', purposeFarming: 'कृषि', purposeEducation: 'शिक्षा', translating: 'अनुवाद हो रहा है...', assessmentComplete: 'आकलन पूरा', voiceUnsupported: 'इस ब्राउज़र में आवाज़ इनपुट समर्थित नहीं है। कृपया टेक्स्ट या संरचित प्रोफ़ाइल का उपयोग करें।', requestRequired: 'कृपया बताएं कि आपको किस सहायता की आवश्यकता है।', serviceUnavailable: 'सेवा इस समय उपलब्ध नहीं है।'
  },
  bn: {
    brandSubtitle: 'বুদ্ধিমান রেয়াতি প্রকল্প মিলান', location: 'ভারত', eyebrowWorkspace: 'আর্থিক সহায়তা কর্মক্ষেত্র', headingMain1: 'শুভ অপরাহ্ণ।', headingMain2: 'চলুন আপনার পরিকল্পনা সম্ভব করি।', introCopy: 'আপনার প্রয়োজন নিজের ভাষায় বলুন। আমরা তা যোগ্যতা যাচাই ও পরবর্তী পদক্ষেপে রূপ দেব।', metricRequired: 'প্রয়োজনীয়', metricIncome: 'বার্ষিক আয়', metricSector: 'ক্ষেত্র', metricStatus: 'বর্তমান অবস্থা', statusEligible: 'যোগ্য', statusReview: 'পর্যালোচনা প্রয়োজন', statusReady: 'বিশ্লেষণের জন্য প্রস্তুত', eyebrowSupport: 'সহায়তা খুঁজুন', titleLookingFor: 'আপনি কী খুঁজছেন বলুন', btnStructured: 'সুশৃঙ্খল প্রোফাইল', btnNatural: 'স্বাভাবিক ভাষা', btnVoice: 'ভয়েস', btnAnalyse: 'যোগ্যতা বিশ্লেষণ করুন', btnAnalysing: 'প্রোফাইল বিশ্লেষণ হচ্ছে...', labelTryExample: 'একটি উদাহরণ চেষ্টা করুন', labelUnderstanding: 'বোঝাপড়া', labelRequirement: 'প্রয়োজন', labelAddRequirement: 'প্রয়োজন যোগ করুন', labelIncome: 'আয়', labelAddIncome: 'আয় যোগ করুন', eyebrowAssessment: 'মূল্যায়ন', titleOutlook: 'আপনার আর্থিক পরিস্থিতি', titleResultsPlaceholder: 'ফলাফল এখানে দেখা যাবে', btnNewAssessment: 'নতুন মূল্যায়ন', descPlaceholderResults: 'বিশ্লেষণের পরে আপনার যোগ্যতা, আর্থিক শর্ত ও সহায়তা অংশীদার দেখা যাবে।', purposeGeneral: 'সাধারণ', purposeTailoring: 'দর্জি', purposeDairy: 'দুগ্ধ', purposeWelding: 'ওয়েল্ডিং', purposeFarming: 'কৃষি', purposeEducation: 'শিক্ষা', translating: 'অনুবাদ হচ্ছে...', assessmentComplete: 'মূল্যায়ন সম্পূর্ণ', voiceUnsupported: 'এই ব্রাউজারে ভয়েস ইনপুট সমর্থিত নয়।', requestRequired: 'আপনার কী সহায়তা প্রয়োজন তা বলুন।', serviceUnavailable: 'পরিষেবা বর্তমানে অনুপলব্ধ।'
  },
  te: {
    brandSubtitle: 'తెలివైన రాయితీ పథకం సరిపోలిక', location: 'భారత్', eyebrowWorkspace: 'ఆర్థిక సహాయ కార్యస్థలం', headingMain1: 'శుభ మధ్యాహ్నం.', headingMain2: 'మీ ప్రణాళికను సాధ్యం చేద్దాం.', introCopy: 'మీ అవసరాన్ని మీ మాటల్లో వివరించండి. దాన్ని అర్హత తనిఖీ మరియు తదుపరి చర్యలుగా మారుస్తాం.', metricRequired: 'అవసరం', metricIncome: 'వార్షిక ఆదాయం', metricSector: 'రంగం', metricStatus: 'ప్రస్తుత స్థితి', statusEligible: 'అర్హులు', statusReview: 'సమీక్ష అవసరం', statusReady: 'విశ్లేషణకు సిద్ధం', eyebrowSupport: 'సహాయం కనుగొనండి', titleLookingFor: 'మీకు ఏమి కావాలో చెప్పండి', btnStructured: 'నిర్మిత ప్రొఫైల్', btnNatural: 'సహజ భాష', btnVoice: 'వాయిస్', btnAnalyse: 'అర్హతను విశ్లేషించండి', btnAnalysing: 'ప్రొఫైల్ విశ్లేషణ జరుగుతోంది...', labelTryExample: 'ఒక ఉదాహరణ ప్రయత్నించండి', labelUnderstanding: 'అవగాహన', labelRequirement: 'అవసరం', labelAddRequirement: 'అవసరాన్ని జోడించండి', labelIncome: 'ఆదాయం', labelAddIncome: 'ఆదాయాన్ని జోడించండి', eyebrowAssessment: 'అంచనా', titleOutlook: 'మీ ఆర్థిక పరిస్థితి', titleResultsPlaceholder: 'ఫలితాలు ఇక్కడ కనిపిస్తాయి', btnNewAssessment: 'కొత్త అంచనా', descPlaceholderResults: 'విశ్లేషణ తర్వాత మీ అర్హత, ఆర్థిక నిబంధనలు మరియు సహాయ భాగస్వాములు కనిపిస్తారు.', purposeGeneral: 'సాధారణ', purposeTailoring: 'టైలరింగ్', purposeDairy: 'పాడి', purposeWelding: 'వెల్డింగ్', purposeFarming: 'వ్యవసాయం', purposeEducation: 'విద్య', translating: 'అనువదిస్తోంది...', assessmentComplete: 'అంచనా పూర్తయింది', voiceUnsupported: 'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్‌కు మద్దతు లేదు.', requestRequired: 'మీకు ఏ సహాయం కావాలో చెప్పండి.', serviceUnavailable: 'సేవ ప్రస్తుతం అందుబాటులో లేదు.'
  },
  mr: {
    brandSubtitle: 'बुद्धिमान सवलतीच्या योजना जुळवणी', location: 'भारत', eyebrowWorkspace: 'आर्थिक सहाय्य कार्यक्षेत्र', headingMain1: 'शुभ दुपार.', headingMain2: 'तुमची योजना शक्य करूया.', introCopy: 'तुमची गरज तुमच्या शब्दांत सांगा. आम्ही तिचे पात्रता तपासणी आणि पुढील कृतींमध्ये रूपांतर करू.', metricRequired: 'आवश्यक', metricIncome: 'वार्षिक उत्पन्न', metricSector: 'क्षेत्र', metricStatus: 'सध्याची स्थिती', statusEligible: 'पात्र', statusReview: 'पुनरावलोकन आवश्यक', statusReady: 'विश्लेषणासाठी तयार', eyebrowSupport: 'मदत शोधा', titleLookingFor: 'तुम्ही काय शोधत आहात ते सांगा', btnStructured: 'संरचित प्रोफाइल', btnNatural: 'नैसर्गिक भाषा', btnVoice: 'आवाज', btnAnalyse: 'पात्रता तपासा', btnAnalysing: 'प्रोफाइलचे विश्लेषण सुरू आहे...', labelTryExample: 'उदाहरण वापरून पहा', labelUnderstanding: 'समज', labelRequirement: 'गरज', labelAddRequirement: 'गरज जोडा', labelIncome: 'उत्पन्न', labelAddIncome: 'उत्पन्न जोडा', eyebrowAssessment: 'मूल्यांकन', titleOutlook: 'तुमचे आर्थिक चित्र', titleResultsPlaceholder: 'निकाल येथे दिसतील', btnNewAssessment: 'नवीन मूल्यांकन', descPlaceholderResults: 'विश्लेषणानंतर तुमची पात्रता, आर्थिक अटी आणि सहाय्य भागीदार दिसतील.', purposeGeneral: 'सामान्य', purposeTailoring: 'शिवणकाम', purposeDairy: 'दुग्धव्यवसाय', purposeWelding: 'वेल्डिंग', purposeFarming: 'शेती', purposeEducation: 'शिक्षण', translating: 'भाषांतर सुरू आहे...', assessmentComplete: 'मूल्यांकन पूर्ण', voiceUnsupported: 'या ब्राउझरमध्ये आवाज इनपुट समर्थित नाही.', requestRequired: 'तुम्हाला कोणत्या मदतीची गरज आहे ते सांगा.', serviceUnavailable: 'सेवा सध्या उपलब्ध नाही.'
  },
  ta: {
    brandSubtitle: 'புத்திசாலித்தனமான சலுகைத் திட்ட பொருத்தி', location: 'இந்தியா', eyebrowWorkspace: 'நிதி உதவி பணியிடம்', headingMain1: 'மதிய வணக்கம்.', headingMain2: 'உங்கள் திட்டத்தை சாத்தியமாக்குவோம்.', introCopy: 'உங்கள் தேவையை உங்கள் சொந்த வார்த்தைகளில் கூறுங்கள். அதைத் தகுதி சரிபார்ப்பாகவும் அடுத்த படிகளாகவும் மாற்றுவோம்.', metricRequired: 'தேவை', metricIncome: 'ஆண்டு வருமானம்', metricSector: 'துறை', metricStatus: 'தற்போதைய நிலை', statusEligible: 'தகுதியானவர்', statusReview: 'மதிப்பாய்வு தேவை', statusReady: 'பகுப்பாய்வுக்கு தயார்', eyebrowSupport: 'ஆதரவைத் தேடுங்கள்', titleLookingFor: 'நீங்கள் தேடுவதைச் சொல்லுங்கள்', btnStructured: 'கட்டமைக்கப்பட்ட சுயவிவரம்', btnNatural: 'இயல்பான மொழி', btnVoice: 'குரல்', btnAnalyse: 'தகுதியை பகுப்பாய்வு செய்', btnAnalysing: 'சுயவிவரம் பகுப்பாய்வு செய்யப்படுகிறது...', labelTryExample: 'ஓர் உதாரணத்தை முயற்சிக்கவும்', labelUnderstanding: 'புரிதல்', labelRequirement: 'தேவை', labelAddRequirement: 'தேவையைச் சேர்க்கவும்', labelIncome: 'வருமானம்', labelAddIncome: 'வருமானத்தைச் சேர்க்கவும்', eyebrowAssessment: 'மதிப்பீடு', titleOutlook: 'உங்கள் நிதி நிலை', titleResultsPlaceholder: 'முடிவுகள் இங்கே தோன்றும்', btnNewAssessment: 'புதிய மதிப்பீடு', descPlaceholderResults: 'பகுப்பாய்வுக்குப் பிறகு உங்கள் தகுதி, நிதி விதிமுறைகள் மற்றும் ஆதரவாளர்கள் தோன்றுவார்கள்.', purposeGeneral: 'பொது', purposeTailoring: 'தையல்', purposeDairy: 'பால் பண்ணை', purposeWelding: 'வெல்டிங்', purposeFarming: 'விவசாயம்', purposeEducation: 'கல்வி', translating: 'மொழிபெயர்க்கப்படுகிறது...', assessmentComplete: 'மதிப்பீடு முடிந்தது', voiceUnsupported: 'இந்த உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை.', requestRequired: 'உங்களுக்கு என்ன உதவி தேவை என்று கூறுங்கள்.', serviceUnavailable: 'சேவை தற்போது கிடைக்கவில்லை.'
  }
}

const locationText = {
  en: { capacityAvailable: 'allocation available', directions: 'Open directions', mapTitle: 'Your location and nearby routing area' },
  hi: { capacityAvailable: 'उपलब्ध आवंटन', directions: 'दिशा खोलें', mapTitle: 'आपका स्थान और आसपास का रूटिंग क्षेत्र' },
  bn: { capacityAvailable: 'উপলব্ধ বরাদ্দ', directions: 'দিকনির্দেশ খুলুন', mapTitle: 'আপনার অবস্থান এবং কাছাকাছি রাউটিং এলাকা' },
  te: { capacityAvailable: 'అందుబాటులో ఉన్న కేటాయింపు', directions: 'దిశలను తెరవండి', mapTitle: 'మీ స్థానం మరియు సమీప రూటింగ్ ప్రాంతం' },
  mr: { capacityAvailable: 'उपलब्ध वाटप', directions: 'दिशानिर्देश उघडा', mapTitle: 'तुमचे स्थान आणि जवळचा मार्ग क्षेत्र' },
  ta: { capacityAvailable: 'கிடைக்கும் ஒதுக்கீடு', directions: 'வழிகளைத் திறக்கவும்', mapTitle: 'உங்கள் இருப்பிடம் மற்றும் அருகிலுள்ள வழித்தடப் பகுதி' }
}

export const getStaticTexts = (code, defaults) => ({ ...defaults, ...shared[code], ...locationText[code] })

const demoContent = {
  hi: [['दर्जी की दुकान · ₹1.2 लाख', 'मुझे दर्जी की दुकान के लिए 1.2 लाख रुपये चाहिए। मेरे परिवार की सालाना आय 150000 रुपये है।'], ['डेयरी फार्म · ₹3 लाख', 'मुझे छोटे डेयरी व्यवसाय के लिए 3 लाख रुपये चाहिए। मेरी सालाना आय 280000 रुपये है।'], ['वेल्डिंग कार्यशाला · ₹5 लाख', 'मुझे वेल्डिंग इकाई के लिए 5 लाख रुपये चाहिए और मेरी सालाना आय 450000 रुपये है।'], ['इंजीनियरिंग कॉलेज · ₹2 लाख', 'मैं छात्र हूं और इंजीनियरिंग पाठ्यक्रम के लिए 2 लाख रुपये चाहता हूं। मेरे परिवार की सालाना आय 300000 रुपये है।']],
  bn: [['দর্জির দোকান · ₹1.2 লক্ষ', 'আমার একটি দর্জির দোকানের জন্য ১.২ লক্ষ টাকা দরকার। আমার পরিবারের বার্ষিক আয় ১৫০০০০ টাকা।'], ['দুগ্ধ খামার · ₹3 লক্ষ', 'একটি ছোট দুগ্ধ ব্যবসার জন্য ৩ লক্ষ টাকা চাই। আমার বার্ষিক আয় ২৮০০০০ টাকা।'], ['ওয়েল্ডিং কর্মশালা · ₹5 লক্ষ', 'একটি ওয়েল্ডিং ইউনিটের জন্য ৫ লক্ষ টাকা দরকার এবং আমার বার্ষিক আয় ৪৫০০০০ টাকা।'], ['ইঞ্জিনিয়ারিং কলেজ · ₹2 লক্ষ', 'আমি ছাত্র এবং ইঞ্জিনিয়ারিং কোর্সের জন্য ২ লক্ষ টাকা চাই। আমার পরিবারের বার্ষিক আয় ৩০০০০০ টাকা।']],
  te: [['టైలరింగ్ దుకాణం · ₹1.2 లక్షలు', 'టైలరింగ్ దుకాణం కోసం నాకు 1.2 లక్షల రూపాయలు కావాలి. నా కుటుంబ వార్షిక ఆదాయం 150000 రూపాయలు.'], ['పాడి ఫారం · ₹3 లక్షలు', 'చిన్న పాడి వ్యాపారం కోసం నాకు 3 లక్షలు కావాలి. నా వార్షిక ఆదాయం 280000.'], ['వెల్డింగ్ వర్క్‌షాప్ · ₹5 లక్షలు', 'వెల్డింగ్ యూనిట్ కోసం నాకు 5 లక్షలు కావాలి, నా వార్షిక ఆదాయం 450000.'], ['ఇంజనీరింగ్ కళాశాల · ₹2 లక్షలు', 'నేను విద్యార్థిని, ఇంజనీరింగ్ కోర్సు కోసం 2 లక్షలు కావాలి. నా కుటుంబ వార్షిక ఆదాయం 300000.']],
  mr: [['शिवणकामाचे दुकान · ₹1.2 लाख', 'शिवणकामाच्या दुकानासाठी मला 1.2 लाख रुपये हवे आहेत. माझ्या कुटुंबाचे वार्षिक उत्पन्न 150000 रुपये आहे.'], ['दुग्ध व्यवसाय · ₹3 लाख', 'छोट्या दुग्ध व्यवसायासाठी मला 3 लाख रुपये हवे आहेत. माझे वार्षिक उत्पन्न 280000 रुपये आहे.'], ['वेल्डिंग कार्यशाळा · ₹5 लाख', 'वेल्डिंग युनिटसाठी मला 5 लाख रुपये हवे आहेत आणि माझे वार्षिक उत्पन्न 450000 रुपये आहे.'], ['अभियांत्रिकी महाविद्यालय · ₹2 लाख', 'मी विद्यार्थी आहे आणि अभियांत्रिकी अभ्यासक्रमासाठी मला 2 लाख रुपये हवे आहेत. माझ्या कुटुंबाचे वार्षिक उत्पन्न 300000 रुपये आहे.']],
  ta: [['தையல் கடை · ₹1.2 லட்சம்', 'தையல் கடைக்கு எனக்கு 1.2 லட்சம் ரூபாய் தேவை. என் குடும்பத்தின் ஆண்டு வருமானம் 150000 ரூபாய்.'], ['பால் பண்ணை · ₹3 லட்சம்', 'சிறிய பால் பண்ணை தொழிலுக்கு எனக்கு 3 லட்சம் வேண்டும். என் ஆண்டு வருமானம் 280000 ரூபாய்.'], ['வெல்டிங் பணிமனை · ₹5 லட்சம்', 'வெல்டிங் பிரிவுக்கு எனக்கு 5 லட்சம் வேண்டும், என் ஆண்டு வருமானம் 450000 ரூபாய்.'], ['பொறியியல் கல்லூரி · ₹2 லட்சம்', 'நான் மாணவன், பொறியியல் படிப்புக்கு 2 லட்சம் தேவை. என் குடும்ப ஆண்டு வருமானம் 300000 ரூபாய்.']]
}

export const getStaticDemos = (code, demos) => demoContent[code]
  ? demos.map((demo, index) => ({ ...demo, label: demoContent[code][index][0], text: demoContent[code][index][1] }))
  : demos
